### ISSUE TITLE
Startup error handling

### ISSUE THREAD

**Issue by NerdGuruDevelopers** [slashtrace/slashtrace#8]
Sometimes startup errors can trigger a failure in slashtrace.

 `Fatal error: Uncaught RuntimeException in vendor/slashtrace/slashtrace/src/StackTrace/StackFrameContextExtractor.php:23
Stack trace:
#0 vendor/slashtrace/slashtrace/src/StackTrace/StackTraceInspector.php(113): SlashTrace\StackTrace\StackFrameContextExtractor->getContext('Unknown', 0)
#1 vendor/slashtrace/slashtrace/src/StackTrace/StackTraceInspector.php(104): SlashTrace\StackTrace\StackTraceInspector->setFrameContext(Object(SlashTrace\StackTrace\StackFrame))
#2 vendor/slashtrace/slashtrace/src/StackTrace/StackTraceInspector.php(25): SlashTrace\StackTrace\StackTraceInspector->getExceptionFrame(Object(ErrorException))
#3 vendor/slashtrace/slashtrace/src/Exception/ExceptionInspector.php(35): SlashTrace\StackTrace\StackTraceInspector->fromException(Object(ErrorException))
#4 endor/slashtrace/slashtrace/src/Exception/ExceptionInspector.php(24): SlashTrace\Exception\ExceptionInspector->getStackTrace(Object(ErrorException))
#5 vendor/slas in /var/www/IPQ/vendor/slashtrace/slashtrace/src/StackTrace/StackFrameContextExtractor.php on line 23`

This issue appears to be caused by getContext receiving an Unknown from the PHP error system. My "solution" in order to be able to see what the error actually was involved adding a:

`if($file === 'Unknown'){
    return [];
}`

Doing so displayed that I had a missing dynamic library (which is the error I'd expect to see in this context).

This may not be the solution to the issue that you want to actually have.

--
Lastly thank you for the library, it's been awesome thus far and I'd donate if you added a button.

**Comment by victorstanciu** [comment]
@NerdGuruDevelopers Thank you very much for reporting this, I'll implement a fix ASAP. Can you give me more info about this, please? Would it be possible to create a small script that reproduces it?

**Comment by NerdGuruDevelopers** [comment]
Add a nonexistent DLL file to your php.ini (extension=doesnotexist.so) and run any CLI application.

**Comment by victorstanciu** [comment]
Fixed and [tagged](https://github.com/slashtrace/slashtrace/releases/tag/1.1.2). Thanks a lot @NerdGuruDevelopers!

**Comment by NerdGuruDevelopers** [comment]
Thanks for your fix, I'll test it shortly.

Do you have a donate link?

**Comment by victorstanciu** [comment]
> Do you have a donate link?

I don't. Knowing that you enjoy using the library and find it useful is enough :) Thank you!
